### ISSUE TITLE
decoder.StreamingDecoder leaks active threads

### ISSUE THREAD

**Issue by hughsw** [sonos/pyFLAC#22]
We have a server that processes flac streams.  We've noticed that the worker thread that StreamingDecoder creates is not always joined when the decoder is finished.  So the number of active threads increases without bound over time.

Looking at the code we see some race conditions.  For instance, the `while` loop in `decoder.py: _read_callback` will never end if this loop is active with an empty `_buffer` at the point in time when the main thread calls `StreamingDecoder.finish()` to set the `_done` flag:
https://github.com/sonos/pyFLAC/blob/e17d0363ae347c1d8f4284d37216e1b602ba67ab/pyflac/decoder.py#L333-L337
(Sigh, the use of `sleep()` and timeouts is always a red-flag in multithreading code anyway.)

We are using a modified version of StreamingDecoder that has no sleeps or timeouts and it doesn't leak threads.  If there's interest we can post a  couple of PRs (including a regression test).

**Comment by shaynemei** [comment]
@hughsw Hi, I noticed this issue as well. Could you kindly share your modified version?

**Comment by brandyn** [comment]
I have submitted a fix ( #25 ) but am unable to test here so if anyone else could run tox on it that would be helpful, thanks!

**Comment by joetoddsonos** [comment]
Thank you all for reporting these issues and improving pyFLAC. The fixes should now be released in https://pypi.org/project/pyFLAC/3.0.0/
